# Copyright (c) IBM Corporation 2020, 2022

# IBM collection namespace
namespace: ibm

# IBM Z System Automation collection
name: ibm_zos_sysauto

# The version of the collection.
version: 1.0.1-beta.2

# Collection README file
readme: README.md

# Contributors
authors:
  - Anke Luedde <lueddea@de.ibm.com>

# A short summary description of the collection
description: The IBM Z System Automation collection includes roles and sample playbooks to access the IBM Z System Automation Operations REST server.

# This collection is licensed under Apache License, Version 2.0
license:
- "Apache-2.0"

# Tags
tags:
  - ibm
  - z
  - zos
  - z_os
  - zos_sa
  - ibm_zos_sa
  - system_automation

# The URL of the originating SCM repository
repository: https://github.com/ansible-collections/ibm_zos_sysauto

# The URL to any online docs
documentation: https://ibm.github.io/z_ansible_collections_doc/index.html

# The URL to the homepage of the collection/project
homepage: https://www.ibm.com/support/knowledgecenter/SSWRCJ_4.2.0/com.ibm.safos.doc_4.2/kc_welcome-444.html

# The URL to the collection issue tracker
issues: https://github.com/ansible-collections/ibm_zos_sysauto/issues

# Ignore files and directories matching the following patterns
build_ignore:
  - .gitignore
  - .github
  - .gitattributes
  - '*.tar.gz'
  - docs
  - changelogs
