---
# Copyright (c) IBM Corporation 2020, 2023

galaxy_info:
  author: Bernd Jostmeyer <bjost@de.ibm.com>
  description: Create and resume a new dynamic resource instance from a template in an IBM Z System Automation environment.
  company: IBM

  platforms:
    - name: GenericLinux
      versions:
        - all

  license: Apache-2.0

  min_ansible_version: "2.9"

  galaxy_tags:
    - ibm
    - z
    - zos
    - z_os
    - zos_sa
    - ibm_zos_sa
    - system_automation
    - infrastructure
    - tools

dependencies: []
